### ISSUE TITLE
Cannot pull adminer design to docker

### ISSUE THREAD

**Issue by khangahs** [Niyko/Hydra-Dark-Theme-for-Adminer#13]
```
 adminer:
    depends_on:
      - db
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: hydra
    restart: always
    ports:
      - "8086:8080"
```

I cannot pull the design on Docker, please help.

**Comment by Matthew-Benson** [comment]
[The repo linked on docker hub](https://github.com/vrana/adminer/tree/master/designs) for themes updated hydra to be a submodule in the repo. I don't know how their theme downloading script works but I suspect that might be the problem because other themes that are directly linked in that repo work fine.

**Comment by Matthew-Benson** [comment]
Yep looks like it's not initializing git submodules when it's looking to pull a theme file. Something like `git submodule update --init --recursive` would do the trick.

Check out the setup script responsible:
https://github.com/TimWolla/docker-adminer/blob/master/4/entrypoint.sh

And the [Dockerfile](https://github.com/TimWolla/docker-adminer/blob/master/4/Dockerfile) doesn't use a git clone - it's pulling a release of adminer so it's not really the image maintainer's responsibility either...

He's pulling down https://github.com/vrana/adminer/releases/download/v4.8.0/adminer-4.8.0.tar.gz (for example) and that release doesn't have anything in the hydra folder... I think if you went back a few releases - probably to something from more than 3 months ago the themes would be working fine.

@Niyko do you have any kind of contact with the adminer maintainers? I'd create an issue on their repo but they don't have issues on their repo lol. Not sure how to report that their build process for releases is broken. They just need to initialize their submodules when they make a new release if they're going to use submodules.

The only workaround I've come up with is to start the container then exec into it elsewhere and `curl -O https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css`

**Comment by khangahs** [comment]
Cool! I will try the solution and see if it’s work when I returned to the
office. It would be a disappointment to not having this theme while working
on docker.

**Comment by TimWolla** [comment]
> And the [Dockerfile](https://github.com/TimWolla/docker-adminer/blob/master/4/Dockerfile) doesn't use a git clone - it's pulling a release of adminer so it's not really the image maintainer's responsibility either...

Hi :wave:

To clarify: I'm just pulling the release for the compiled Adminer “binary”. For plugins and themes I (need to) use the archive tarball. @Reintjuu reported this issue in my repository at https://github.com/TimWolla/docker-adminer/issues/106 if you want to follow along or chime in.

**Comment by geekyouth** [comment]
```shell
wget https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css 
```
docker-compose 

```yaml
...
  adminer:
    image: adminer:4.8.1-standalone
    hostname: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql57
      ADMINER_DESIGN: hydra
    volumes:
      - ./adminer.css:/var/www/html/designs/hydra/adminer.css
    networks:
      - fullstack
...
```
![image](https://github.com/Niyko/Hydra-Dark-Theme-for-Adminer/assets/12899262/515ae358-c2c5-44e5-9117-2d7b3460686d)
![image](https://github.com/Niyko/Hydra-Dark-Theme-for-Adminer/assets/12899262/82a252bc-09a9-48bb-b984-ebab7e2f4431)
