### ISSUE TITLE
Some UI doesn't look right

### ISSUE THREAD

**Issue by ppazos** [Niyko/Hydra-Dark-Theme-for-Adminer#15]
In my 14" laptop, the database selector on the menu dis displayed as two lines, the buttons below have their text exceeding the size of the button, and the table list below is really far down and small.

![Screenshot_2022-07-01_15-30-57](https://user-images.githubusercontent.com/1278556/176951720-583b372e-cc4e-4a61-a32e-5b4e3b3b7d99.png)

This makes this design difficult to use. The rest looks nice.

**Comment by NzoSifou** [comment]
Same problem here when I have to select a db (don't pay attention to French)
![image](https://user-images.githubusercontent.com/54418244/210208042-0987dda9-b0c8-4470-ba0e-50aa64ad84b7.png)

**Comment by geekyouth** [comment]
```shell
wget https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css 
```
docker-compose 

```yaml
...
  adminer:
    image: adminer:4.8.1-standalone
    hostname: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql57
      ADMINER_DESIGN: hydra
    volumes:
      - ./adminer.css:/var/www/html/designs/hydra/adminer.css
    networks:
      - fullstack
...
```
![image](https://github.com/Niyko/Hydra-Dark-Theme-for-Adminer/assets/12899262/515ae358-c2c5-44e5-9117-2d7b3460686d)
![image](https://github.com/Niyko/Hydra-Dark-Theme-for-Adminer/assets/12899262/82a252bc-09a9-48bb-b984-ebab7e2f4431)
