### ISSUE TITLE
Where is the adminer.php file in the Docker image?

### ISSUE THREAD

**Issue by Nefcanto** [Niyko/Hydra-Dark-Theme-for-Adminer#21]
Hello. I'm using the Adminer's official docker image:

```
    admin:
        image: adminer
        ports:
            - 7401:8080
        environment:
            - ADMINER_DEFAULT_SERVER=database
```

But I can't find the `adminer.php` file. I searched the entire container:

```
root@database:/# find -type f -name Adminer.php 2>/dev/null
root@database:/# find -type f -name adminer.php 2>/dev/null
root@database:/# 
```

Where is the `adminer.php` file in the Docker container?
